name: trading-strategist
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # Core dependencies
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - scikit-learn=1.3.0
  - pyyaml=6.0.1
  - scipy=1.10.1
  # Optional dependencies for interactive development
  - jupyter=1.0.0
  - ipywidgets=8.0.7
  # Development tools
  - pytest=7.4.0
  - black=23.7.0
  - flake8=6.1.0
  - isort=5.12.0
  - mypy=1.4.1
  # Additional conda-forge packages
  - pip
  - streamlit=1.27.0
  # Data fetching packages
  - yfinance=0.2.31