# Combined Strategy Evaluation Configuration
# This config evaluates all three strategies together for direct comparison

experiment:
  name: "Combined Strategy Comparison"
  output_prefix: "combined_strategy"  # This ensures separate output files

data:
  symbol: "JPM"
  training:
    start_date: "2008-01-01"
    end_date: "2009-12-31"
  testing:
    start_date: "2010-01-01"
    end_date: "2011-12-31"

portfolio:
  starting_value: 100000

# Explicitly list all models to evaluate
models:
  - manual           # Rule-based manual strategy
  - strategy_learner # Tree-based strategy learner
  - q_strategy_learner # Q-learning strategy

# Tree Strategy parameters
dt_strategy:
  # Technical indicator parameters
  window_size: 20
  rsi_window: 14
  stoch_window: 14
  cci_window: 20
  buy_threshold: 0.02
  sell_threshold: -0.02
  position_size: 1000
  prediction_days: 5
  
  # Tree parameters
  leaf_size: 5
  bags: 20
  boost: false

# Q-Strategy parameters
q_strategy:
  # Technical indicator parameters
  indicator_bins: 10
  window_size: 20
  rsi_window: 14
  position_size: 1000
  max_iterations: 100
  
  # Q-Learning parameters
  learning_rate: 0.2
  discount_factor: 0.9
  random_action_rate: 0.5
  random_action_decay: 0.99
  dyna_iterations: 10

# Manual strategy parameters
manual_strategy:
  position_size: 1000
  window_size: 20
  rsi_window: 14

trading:
  commission: 9.95
  impact: 0.005

visualization:
  include_benchmark: true   # Include buy & hold benchmark
  plot_comparison: true     # Generate performance comparison chart
  plot_decision_tree: true  # Include decision tree visualization
  plot_learning_curve: true # Include Q-learning curve visualization