# Strategy comparison experiment

experiment:
  name: "Strategy Comparison"
  description: "Compare Manual Strategy vs Decision Tree Strategy"
  output_prefix: "strategy_comparison"

data:
  symbol: "JPM"
  in_sample:
    start_date: "2008-01-01"
    end_date: "2009-12-31"
  out_sample:
    start_date: "2010-01-01"
    end_date: "2011-12-31"

portfolio:
  starting_value: 100000
  max_positions: 1000  # Configurable position size for benchmark

# Changed from strategy_learner to dt_strategy for consistency
dt_strategy:
  window_size: 20
  rsi_window: 14
  stoch_window: 14
  cci_window: 20
  position_size: 1000
  buy_threshold: 0.02
  sell_threshold: -0.02
  prediction_days: 5
  leaf_size: 5
  bags: 20
  boost: false
  
manual_strategy:
  window_size: 20
  rsi_window: 14
  stoch_window: 14
  cci_window: 20
  position_size: 1000
  
trading:
  commission: 9.95
  impact: 0.005

performance:
  risk_free_rate: 0.0
  sampling_frequency: 252.0

visualization:
  compare_returns: true
  plot_indicators: true
  metrics_table: true
  fig_size: [12, 8]
  colors:
    manual_strategy: "red"
    ml_strategy: "blue"
    benchmark: "purple"