data:
  symbol: JPM
  testing:
    end_date: '2011-12-31'
    start_date: '2010-01-01'
  training:
    end_date: '2009-12-31'
    start_date: '2008-01-01'
experiment:
  description: Rule-based technical indicator trading strategy vs benchmark
  name: Manual Trading Strategy Evaluation
  output_prefix: manual_strategy
manual_strategy:
  buy_threshold: 0.02
  cci_window: 20
  indicator_thresholds:
    bollinger_lower: -1.0
    bollinger_upper: 1.0
    cci_lower: -100
    cci_upper: 100
    min_vote_buy: 3
    min_vote_sell: 3
    rsi_lower: 30
    rsi_upper: 70
    stoch_lower: 20
    stoch_upper: 80
  position_size: 1000
  rsi_window: 14
  sell_threshold: -0.02
  stoch_window: 14
  window_size: 20
performance:
  risk_free_rate: 0.0
  sampling_frequency: 252.0
portfolio:
  max_positions: 1000
  starting_value: 100000
trading:
  commission: 9.95
  impact: 0.005
visualization:
  annotate_trades: true
  colors:
    benchmark: purple
    manual_strategy: red
  compare_returns: true
  fig_size:
  - 12
  - 8
  metrics_table: true
  plot_indicators: true
  trade_markers:
    alpha: 0.5
    buy_color: blue
    line_style: --
    sell_color: black
