data:
  symbol: JPM
  testing:
    end_date: '2011-12-31'
    start_date: '2010-01-01'
  training:
    end_date: '2009-12-31'
    start_date: '2008-01-01'
experiment:
  name: Q-Learning Strategy Analysis
  output_prefix: qstrategy
models:
- q_strategy_learner
- manual
portfolio:
  starting_value: 100000
q_strategy_learner:
  bb_range:
  - -2.0
  - 2.0
  cci_norm: 200.0
  cci_range:
  - -2.0
  - 2.0
  cci_window: 20
  convergence_threshold: 0.1
  discount_factor: 0.9
  dyna_iterations: 10
  indicator_bins: 10
  learning_rate: 0.2
  macd_range:
  - -1.0
  - 1.0
  max_iterations: 100
  min_iterations: 20
  momentum_periods:
  - 3
  - 5
  - 10
  position_size: 1000
  random_action_decay: 0.99
  random_action_rate: 0.5
  rsi_norm: 100.0
  rsi_range:
  - 0.0
  - 1.0
  rsi_window: 14
  stoch_norm: 100.0
  stoch_range:
  - 0.0
  - 1.0
  stoch_window: 14
  use_bb: true
  use_cci: false
  use_macd: true
  use_rsi: true
  use_stoch: false
  window_size: 20
trading:
  commission: 9.95
  impact: 0.005
visualization:
  include_benchmark: true
  plot_learning_curve: true
