data:
  symbol: JPM
  testing:
    end_date: '2011-12-31'
    start_date: '2010-01-01'
  training:
    end_date: '2009-12-31'
    start_date: '2008-01-01'
experiment:
  name: Decision Tree Strategy Analysis
  output_prefix: tree_strategy
models:
- manual
- tree_strategy_learner
portfolio:
  starting_value: 100000
trading:
  commission: 9.95
  impact: 0.005
tree_strategy_learner:
  bags: 20
  boost: false
  buy_threshold: 0.02
  cci_norm: 200.0
  cci_window: 20
  leaf_size: 5
  momentum_periods:
  - 3
  - 5
  - 10
  position_size: 1000
  prediction_days: 5
  rsi_norm: 100.0
  rsi_window: 14
  sell_threshold: -0.02
  stoch_norm: 100.0
  stoch_window: 14
  window_size: 20
visualization:
  include_benchmark: true
  plot_decision_tree: true
